### ISSUE TITLE
AttributeError: 'Calculation' object has no attribute 'setup_complete'

### ISSUE THREAD

**Issue by MKCarter** [michellab/a3fe#1]
Hi,

Thanks for sharing this code. I am trying to run the example as per the instructions found [here](https://a3fe.readthedocs.io/en/latest/getting_started.html#quick-start) - however, after copying all the inputs into a new folder named test_input - I am seeing an error when running the following code:

```
import a3fe as a3 
calc = a3.Calculation(ensemble_size=5)
calc.setup()
calc.get_optimal_lam_vals()
calc.run(adaptive=False, runtime = 5) # Run non-adaptively for 5 ns per replicate
calc.wait()
calc.set_equilibration_time(1) # Discard the first ns of simulation time
calc.analyse()
calc.save()
```

The error appears to be related to the `calc.setup()` missing some attributes. The error is as follows:

```
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ ❱ 1 calc.setup()                                                                                 │
│   2 calc.get_optimal_lam_vals()                                                                  │
│   3 calc.run(adaptive=False, runtime = 5) # Run non-adaptively for 5 ns per replicate            │
│   4 calc.wait()                                                                                  │
│                                                                                                  │
│ /home/michaelcarter/DD_tools/a3fe/a3fe/run/calculation.py:176 in setup                           │
│                                                                                                  │
│   173 │   │   │   configuration is used.                                                         │
│   174 │   │   """                                                                                │
│   175 │   │                                                                                      │
│ ❱ 176 │   │   if self.setup_complete:                                                            │
│   177 │   │   │   self._logger.info("Setup already complete. Skipping...")                       │
│   178 │   │   │   return                                                                         │
│   179                                                                                            │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'Calculation' object has no attribute 'setup_complete'
```

Do you have any idea on how I can find a fix for this? 

Many Thanks,
Mike

**Comment by fjclark** [comment]
Hi,

Thanks for the clear issue! The `Calculation` object's `setup_complete` attribute should be set when `__init__` is called, but this only happens when the `Calculation` isn't loaded from a a pickle file (see [here](https://github.com/michellab/a3fe/blob/d1f89371e0a6f05ddb7a0371a84050af9de5aa81/a3fe/run/calculation.py#L102). It's assumed that the pickled object was properly set up, but the issue may be that there was an error the first time you ran the above script (e.g. missing input files) before `setup_complete` was set, and that this was re-read from the pickled object when you fixed the error. 

If this is the case, just delete all the non-input files (`Calculation.pkl` is the critical one, but also clean out `Calculation.log` and any `bound` or `free` directories) and try again. If that's not the issue, I'll try and reproduce locally. 

Either way, I should make sure that partially-initialised pickles get ignored when re-running.

Thanks,
Finlay

**Comment by fjclark** [comment]
Also,

>after copying all the inputs into a new folder named test_input

The `Calculation` object expects that the input directory is called `input`, so be sure to either rename it or to specify `calc = a3.Calculation(ensemble_size=5, input_dir="test_input")`, where you're creating the `Calculation` object in the directory containing the `input` directory.

Thanks.

**Comment by MKCarter** [comment]
Hi,

Thanks for the suggestions! This worked perfectly :) 
```
INFO - 2024-07-04 11:25:35,161 - Calculation_0 - Found all required input files for preparation stage preequilibrated
INFO - 2024-07-04 11:25:35,162 - Calculation_0 - Modifying/ creating legs
INFO - 2024-07-04 11:25:35,162 - Calculation_0 - Setting up bound leg...
INFO - 2024-07-04 11:25:35,162 - Leg (type = BOUND)_1 - Found all required input files for preparation stage preequilibrated
INFO - 2024-07-04 11:25:35,162 - Leg (type = BOUND)_1 - Setting up leg...
INFO - 2024-07-04 11:25:35,162 - Leg (type = BOUND)_1 - Creating stage input directories...
INFO - 2024-07-04 11:25:35,163 - Leg (type = BOUND)_1 - Found 1 ensemble equilibration directories already run.
INFO - 2024-07-04 11:25:35,254 - Leg (type = BOUND)_1 - Running ensemble equilibration 1 of 4. Submitting through SLURM...
INFO - 2024-07-04 11:25:35,255 - VirtualQueue - Job (virtual_job_id = 0, slurm_job_id= None), status = JobStatus.QUEUED submitted
```
Many Thanks!

**Comment by fjclark** [comment]
Great! No problem. I've updated the code to avoid this happening again - this will be the 0.1.1 release.
