### ISSUE TITLE
How to use prm and rst files with prepared system?

### ISSUE THREAD

**Issue by ErikZhang-9762** [michellab/a3fe#4]
Hi, 

Thanks for developing the package! Is there a more flexible way to use A3FE? I want to use my own prepared system (already solvated, minimized, equilibrated) . And, using the prepared prm and rst as a starting point.

This allows for more flexibility, for example, for membrane protein systems.

Do you have any idea to do this?

Many Thanks,
Eric

**Comment by fjclark** [comment]
Hi,

Thanks for your interest! Yes, the list of names corresponding to different preparation stages is given [here](https://a3fe.readthedocs.io/en/latest/guides.html#preparing-input-for-a3fe). So for inputs which are already equilibrated, you need to name these `bound_preequil.prm7`/`bound_preequil.rst7` for the bound leg and `free_preequil.prm7`/`free_preequil.rst7` for the free leg. `a3fe` will skip the redundant steps. Note that the "ensemble equilibration" simulations will still be carried out to a) fit the restraints for the bound leg and b) generate diverse starting configurations for each of the replicate ABFE runs (you can change the length of these by modifying the `SystemPreparationConfig` - see [here](https://a3fe.readthedocs.io/en/latest/guides.html#customising-calculations)).

However, I would recommend against using the current version of `a3fe` for membrane protein systems - SOMD (Sire/ OpenMM Molecular Dynamics, part of Sire) is used for the free energy calculations (after setup with GROMACS), and currently SOMD doesn't support PME and uses an isotropic barostat. Allowing the user to switch out SOMD for GROMACS is on my to-do list (I'll make an issue now), but it will be at least a few months until I have time to do this.

Thanks,
Finlay

**Comment by fjclark** [comment]
A good option for ABFE with GROMACS is [this ABFE workflow](https://github.com/bigginlab/ABFE_workflow).

Cheers,
Finlay

**Comment by ErikZhang-9762** [comment]
Thanks for the detailed reply, I will try it tomorrow.

Hope you have a good day.

Cheers，
Eric

**Comment by fjclark** [comment]
Hi @ErikZhang-9762 - did this work for you? Feel free to close the issue if so.

Cheers,
Finlay

**Comment by ErikZhang-9762** [comment]
This work for me. Close this issue now. 

Thanks,
Eric
