### ISSUE TITLE
cpu gromacs version installed with yaml file

### ISSUE THREAD

**Issue by raweru** [michellab/a3fe#9]
The provided YAML file installs a version of GROMACS with OpenCL support instead of CUDA. As a result, despite GPU availability, the simulations run on the CPU.

**Comment by fjclark** [comment]
Thanks for raising. I'm unable to reproduce this (I've tried on two machines).  The only package in `environment.yaml` I can imagine might pull in GROMACS is BioSimSpace (or Sire, which BioSimSpace requires). However, I've chatted with the developer of BioSimSpace and neither should pull in GROMACS.

Did you install into clean environment, or did you install into an existing environment/ alongside other packages which depend on GROMACS? Could you also confirm that you are running on Linux? If you are installing into a clean environment on Linux and still seeing GROMACS pulled in, could you please run `mamba env create -f environment.yaml -v > conda_install_log.txt 2>&1` and share the log?

Thanks.

**Comment by raweru** [comment]
Sorry I just realized I installed the test_env.yaml!

**Comment by fjclark** [comment]
No problem!
